config/routes.rb
WkmBcmsNamespaces::Engine.routes.draw do
  resources :namespaces
end

app/models/wkm_bcms_namespaces/namespace.rb
module WkmBcmsNamespaces
  class Namespace < ActiveRecord::Base
    self.table_name = Cms::Namespacing.prefix("namespaces")
    attr_accessible :name, :section_id

    belongs_to :section, :class_name => "Cms::Section"

    validates_presence_of :section, :name

    def path
      name.slugify.gsub(/\-/, '_')
    end
  end
end

app/controllers/wkm_bcms_namespaces/application_controller.rb
module WkmBcmsNamespaces
  class ApplicationController < ActionController::Base
  end
end

app/controllers/wkm_bcms_namespaces/namespaces_controller.rb
require_dependency "wkm_bcms_namespaces/application_controller"

module WkmBcmsNamespaces
  class NamespacesController < ApplicationController
    include Cms::Authentication::Controller

    before_filter :login_required

    def authorized?
      current_user.permissions.include? Cms::Permission.find_by_name("administrate")
    end

    # GET /namespaces
    # GET /namespaces.json
    def index
      @namespaces = Namespace.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @namespaces }
      end
    end
  
    # GET /namespaces/1
    # GET /namespaces/1.json
    def show
      @namespace = Namespace.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @namespace }
      end
    end
  
    # GET /namespaces/new
    # GET /namespaces/new.json
    def new
      @namespace = Namespace.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @namespace }
      end
    end
  
    # GET /namespaces/1/edit
    def edit
      @namespace = Namespace.find(params[:id])
    end
  
    # POST /namespaces
    # POST /namespaces.json
    def create
      @namespace = Namespace.new(params[:namespace])
  
      respond_to do |format|
        if @namespace.save
          format.html { redirect_to @namespace, notice: 'Namespace was successfully created.' }
          format.json { render json: @namespace, status: :created, location: @namespace }
        else
          format.html { render action: "new" }
          format.json { render json: @namespace.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PUT /namespaces/1
    # PUT /namespaces/1.json
    def update
      @namespace = Namespace.find(params[:id])
  
      respond_to do |format|
        if @namespace.update_attributes(params[:namespace])
          format.html { redirect_to @namespace, notice: 'Namespace was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @namespace.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /namespaces/1
    # DELETE /namespaces/1.json
    def destroy
      @namespace = Namespace.find(params[:id])
      @namespace.destroy
  
      respond_to do |format|
        format.html { redirect_to namespaces_url }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/wkm_bcms_namespaces/application_helper.rb
module WkmBcmsNamespaces
  module ApplicationHelper
    def namespaces_drop_down(form, options={})
      options[:field_name] ||= :namespace_id
      namespaces = options[:section].nil? ? Namespace.order("name ASC") : Namespace.where(:section_id => options[:section].id).order("name ASC")

      form.cms_drop_down options[:field_name], namespaces.collect{ |ns| ["#{ns.name} (#{ns.section.name})", ns.id] }.unshift(["", ""])
    end

    # Generates a drop down form input to select the view to use in a portlet instance
    def layouts_drop_down(form, portlet_name)
      form.cms_drop_down :layout,
                      ActionController::Base.view_paths.map{ |p|
                        # Maps the portlet views directories
                        Dir["#{p}/portlets/#{portlet_name}/*"]
                      }.flatten.delete_if{ |p|
                        # Remove partials from selection
                        File.basename(p).match /^_/
                      }.map { |f|
                        view_file = File.basename(f)
                        [Cms::PageTemplate.display_name(view_file), view_file]
                      }
    end
  end
end

app/helpers/wkm_bcms_namespaces/namespaces_helper.rb
module WkmBcmsNamespaces
  module NamespacesHelper
  end
end

app/views/cms/file_blocks/_form.html.erb
<%= f.cms_text_field :name %>
<%= namespaces_drop_down(f) %>
<%= f.cms_file_field :file, :label => "File", :instructions=>"Select a file to upload.", edit_path: true, edit_section: true %>
<%= f.cms_tag_list %>

app/views/cms/html_blocks/_form.html.erb
<%= f.cms_text_field :name %>
<%= namespaces_drop_down(f) %>
<%= f.cms_text_editor :content %>
<%= f.cms_tag_list %>

app/views/cms/image_blocks/_form.html.erb
<%= f.cms_text_field :name %>
<%= namespaces_drop_down(f) %>
<%= f.cms_file_field :file, :label => "File", :instructions=>"Select a file to upload.", edit_path: true, edit_section: true %>
<%= f.cms_tag_list %>

app/views/layouts/wkm_bcms_namespaces/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WkmBcmsNamespaces</title>
  <%= stylesheet_link_tag    "wkm_bcms_namespaces/application", :media => "all" %>
  <%= javascript_include_tag "wkm_bcms_namespaces/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/wkm_bcms_namespaces/namespaces/_form.html.erb
<%= form_for(@namespace) do |f| %>
  <% if @namespace.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@namespace.errors.count, "error") %> prohibited this namespace from being saved:</h2>

      <ul>
      <% @namespace.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :section_id %><br />
    <%= f.select :section_id, Cms::Section.order(:name).collect { |s| [s.name, s.id] } %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wkm_bcms_namespaces/namespaces/edit.html.erb
<h1>Editing namespace</h1>

<%= render 'form' %>

<%= link_to 'Show', @namespace %> |
<%= link_to 'Back', namespaces_path %>

app/views/wkm_bcms_namespaces/namespaces/index.html.erb
<h1>Listing namespaces</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Section</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @namespaces.each do |namespace| %>
  <tr>
    <td><%= namespace.name %></td>
    <td><%= "#{namespace.section.name} (#{namespace.section.path})" %></td>
    <td><%= link_to 'Show', namespace %></td>
    <td><%= link_to 'Edit', edit_namespace_path(namespace) %></td>
    <td><%= link_to 'Destroy', namespace, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Namespace', new_namespace_path %>

app/views/wkm_bcms_namespaces/namespaces/new.html.erb
<h1>New namespace</h1>

<%= render 'form' %>

<%= link_to 'Back', namespaces_path %>

app/views/wkm_bcms_namespaces/namespaces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @namespace.name %>
</p>

<p>
  <b>Section:</b>
  <%= "#{@namespace.section.name} (#{@namespace.section.path})" %>
</p>


<%= link_to 'Edit', edit_namespace_path(@namespace) %> |
<%= link_to 'Back', namespaces_path %>